name: Deploy Flutter Web

on:
  push:
    branches:
      - my-new-branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter Web
        run: |
          cd f2
          flutter pub get
          flutter build web --release --base-href=/my-flutter-demo/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Flutter build
        uses: actions/upload-pages-artifact@v4
        with:
          path: f2/build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
